version: "3"

networks:
    network:

services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        restart: always
        ports:
            - "80:80"
        volumes:
            - ./src:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - network

    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php
        restart: always
        volumes:
            - ./src:/var/www
        ports:
            - "9000:9000"
        networks:
            - network
        environment: 
            APP_NAME: 'Laravel with Docker'
            APP_ENV: development
            APP_KEY: 'base64:k7kJ2ZhdF9gltXivCE3WOGFqpIV3gsnv40s+mgK5bRg='
            APP_DEBUG: 'true'
            APP_URL: 'localhost:80'


    composer:
        image: composer:1.9
        command: ["composer", "install"]
        restart: always
        volumes:
            # why app???
            - ./src:/app
