version: "3"

networks:
    network:

services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        ports:
            - "8080:80"
        volumes:
            - ./src:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - network

    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php
        volumes:
            - ./src:/var/www
        ports:
            - "9000:9000"
        networks:
            - network

    #composer:
    #    image: composer:1.9
    #    command: ["composer", "install"]
    #    volumes:
            # why app???
    #        - ./src:/app
